# versions

FROM eserozvataf/nodejs-lambda:24 AS upstream-runner

# install dependencies first to improve caching
COPY ./package.json ./package-lock.json ./
RUN npm ci --omit=dev

# copy the rest of the application
COPY . ./

# pass the name of the function handler as an argument to the runtime
CMD ["index.handler"]
